version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: development
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.10
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.13
    - 7.13.14
    - 7.13.8
  - dependency-name: y18n
    versions:
    - 4.0.1
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.12.11
    - 7.12.13
    - 7.12.16
    - 7.12.17
    - 7.13.10
    - 7.13.12
    - 7.13.8
    - 7.13.9
  - dependency-name: eslint
    versions:
    - 7.18.0
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
  - dependency-name: postcss-loader
    versions:
    - 4.2.0
    - 5.0.0
    - 5.1.0
  - dependency-name: semantic-release
    versions:
    - 17.2.3
    - 17.3.9
    - 17.4.0
    - 17.4.1
  - dependency-name: "@babel/plugin-transform-react-jsx"
    versions:
    - 7.12.16
    - 7.12.17
  - dependency-name: autoprefixer
    versions:
    - 10.2.4
  - dependency-name: webpack-cli
    versions:
    - 4.5.0
    - 4.5.0
  - dependency-name: webpack
    versions:
    - 4.46.0
    - 5.21.2
    - 5.21.2
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.4
    - 1.3.5
    - 1.3.6
  - dependency-name: "@babel/plugin-transform-async-to-generator"
    versions:
    - 7.12.1
    - 7.12.13
  - dependency-name: sass-loader
    versions:
    - 10.1.1
  - dependency-name: ini
    versions:
    - 1.3.8
  - dependency-name: css-loader
    versions:
    - 5.0.1
  - dependency-name: npm-user-validate
    versions:
    - 1.0.1
- package-ecosystem: composer
  directory: "/"
  schedule:
    interval: monthly
  open-pull-requests-limit: 10
  target-branch: development
